spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:users
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false

logging-level: INFO

logging:
  level:
    org.jetbrains.kotlin.*: ${logging-level}
    com.sun.*: ${logging-level}
    org.apache.*: ${logging-level}
    org.apache.http.impl.client: ${logging-level}
    org.springframework.security.web.*: ${logging-level}
    org.springframework.web: ${logging-level}
    org.springframework.web.client.RestTemplate: ${logging-level}
    org.springframework.cloud: ${logging-level}
    org.springframework.integration: ${logging-level}
    org.springframework.ws.client.MessageTracing.sent: ${logging-level}
    org.springframework.ws.client.MessageTracing.received: ${logging-level}
    root: ${logging-level}
    api.*: ${logging-level}